# fly.toml app configuration file generated for koestner on 2023-05-27T12:49:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "koestner"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[processes]
  web = "gunicorn app:server"
#  worker = "python folioflex/utils/cq.py" # no longer deploying worker

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 6
